services:
  app:
    build:
      context: /home/neighbor/Etri/etri_nodejs
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=neighbor
      - MYSQL_PASSWORD=spdlqj21
      - MYSQL_DATABASE=etri_test
    depends_on:
      - mysql
    command: ["/usr/src/app/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dev"]

  mysql:
      image: mysql:latest
      container_name: mysql_container
      environment:
        MYSQL_ROOT_PASSWORD: spdlqj21
        MYSQL_DATABASE: etri_test
        MYSQL_USER: neighbor
        MYSQL_PASSWORD: spdlqj21
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
