services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: spdlqj21
      MYSQL_DATABASE: etri_test
      MYSQL_USER: neighbor
      MYSQL_PASSWORD: spdlqj21
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: